from github import Github
import os
import base64
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def get_repo():
    """Lazy initialization of GitHub client"""
    g = Github(os.getenv("GITHUB_TOKEN"))
    return g.get_repo(os.getenv("GITHUB_REPO"))

def create_pr(title: str, body: str, branch: str, files: dict, screenshots: list = None, dump_data: dict = None):
    """
    Create a pull request with file changes, screenshots, and exploitation evidence

    Args:
        title: PR title
        body: PR description
        branch: Branch name
        files: Dict of file paths to content
        screenshots: List of screenshot URLs
        dump_data: Dict containing DB dump information
    """
    try:
        repo = get_repo()

        # Enhance PR body with exploitation details
        enhanced_body = generate_enhanced_pr_body(body, screenshots, dump_data)

        # files = {"path/to/file.py": "new content"}
        try:
            base = repo.get_branch("master")
        except:
            base = repo.get_branch("main")

        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base.commit.sha)

        # Upload files
        for path, content in files.items():
            try:
                f = repo.get_contents(path, ref=base.name)
                repo.update_file(path, f"[AutoCTF] Patch {path}", content, f.sha, branch=branch)
            except:
                repo.create_file(path, f"[AutoCTF] Add {path}", content, branch=branch)

        # Create PR with enhanced body
        pr = repo.create_pull(title=title, body=enhanced_body, head=branch, base=base.name)

        print(f"✅ PR created: {pr.html_url}")
        return pr.html_url

    except Exception as e:
        print(f"GitHub PR creation failed: {e}")
        return f"https://github.com/{os.getenv('GITHUB_REPO')}/pulls"


def generate_enhanced_pr_body(original_body: str, screenshots: list, dump_data: dict):
    """Generate an enhanced PR body with exploitation evidence"""

    body_parts = [
        "# 🎯 AutoCTF Security Patch",
        "",
        original_body,
        "",
        "---",
        "",
        "## 🔥 EXPLOITATION EVIDENCE",
        ""
    ]

    # Add dump summary if available
    if dump_data and dump_data.get('summary'):
        body_parts.extend([
            "### 💀 SQLi Exploitation Summary",
            "```",
            dump_data['summary'],
            "```",
            ""
        ])

    # Add database enumeration
    if dump_data and dump_data.get('databases'):
        body_parts.extend([
            "### 💾 Databases Compromised",
            ""
        ])
        for db in dump_data['databases']:
            body_parts.append(f"- ✅ `{db}` - **DUMPED**")
        body_parts.append("")

    # Add credentials if found
    if dump_data and dump_data.get('credentials'):
        body_parts.extend([
            "### 🔑 Credentials Extracted",
            "",
            f"⚠️ **{len(dump_data['credentials'])} credential entries found in database dump**",
            "",
            "<details>",
            "<summary>View Extracted Credentials (Click to expand)</summary>",
            "",
            "```"
        ])
        for cred in dump_data['credentials'][:5]:  # Limit to first 5
            body_parts.append(cred)
            body_parts.append("---")
        body_parts.extend([
            "```",
            "</details>",
            ""
        ])

    # Add screenshots
    if screenshots:
        body_parts.extend([
            "### 📸 Proof of Exploitation",
            "",
            "*Screenshots captured during DB dump:*",
            ""
        ])
        for i, screenshot_url in enumerate(screenshots, 1):
            # Try to embed as image if it's a valid URL
            if screenshot_url and screenshot_url.startswith("http"):
                body_parts.append(f"![Exploitation Screenshot {i}]({screenshot_url})")
            else:
                body_parts.append(f"- Screenshot {i}: `{screenshot_url}`")
        body_parts.append("")

    # Add remediation info
    body_parts.extend([
        "---",
        "",
        "## 🛡️ REMEDIATION",
        "",
        "This PR contains automated patches generated by AutoCTF's AI engine to fix the exploited vulnerabilities.",
        "",
        "### ⚡ IMMEDIATE ACTIONS REQUIRED:",
        "1. 🔍 **Review** - Carefully review all code changes in this PR",
        "2. 🧪 **Test** - Run your test suite to ensure patches don't break functionality",
        "3. 🔒 **Deploy** - Merge and deploy ASAP to close the vulnerability",
        "4. 🔑 **Rotate** - Change all credentials that may have been exposed",
        "5. 📊 **Audit** - Check logs for signs of exploitation",
        "",
        "### 🎯 Attack Vector:",
        "The vulnerability was exploited using automated SQLi techniques with full database enumeration.",
        "An attacker could have:",
        "- Extracted all database contents",
        "- Stolen user credentials and PII",
        "- Modified or deleted data",
        "- Potentially gained shell access",
        "",
        "---",
        "",
        "🤖 **Generated by AutoCTF** - Autonomous Pentesting & Patching Agent",
        "",
        f"*This PR was created automatically. Review carefully before merging.*"
    ])

    return "\n".join(body_parts)